# Generated by Django 3.1.5 on 2021-06-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netflix',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='netflix',
            old_name='IMDB_Score',
            new_name='imbb_score',
        ),
        migrations.RenameField(
            model_name='netflix',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='netflix',
            old_name='Premiere',
            new_name='premiere',
        ),
        migrations.RenameField(
            model_name='netflix',
            old_name='Runtime',
            new_name='runtime',
        ),
        migrations.RenameField(
            model_name='netflix',
            old_name='Title',
            new_name='title',
        ),
    ]
